WIP: documentation
flatsurf/e-antic pull request #160
Opened 2021-01-02 14:35 UTC by videlec

Provides standardize documentation to the C library and its C++ interface.

- [ ] integration of the Python documentation

2021-01-31 21:27 UTC, saraedum commented
@videlec in principle the docbuild should work now. Note that you need some packages such as sphinx, mkdocs, standardese installed, see `doc/environment.yml`.

```
make # so `import pyeantic` works for sphinx
make html # builds into doc/manual/html
```

To start a webserver locally, you can run `make serve` in `doc/manual`.

The documentation that standardese creates still needs quite some polishing from my end, see, e.g., the todo list at the top of this PR. But at least something is working already.

2021-01-31 21:51 UTC, videlec commented
Maybe we should fix #172 here? Also, where do we specify documentation build dependencies for conda?

2021-01-31 21:53 UTC, saraedum commented
> Also, where do we specify documentation build dependencies for conda?

What do you mean? Where do we explain what is needed to build the documentation?

2021-01-31 21:55 UTC, videlec commented
> > Also, where do we specify documentation build dependencies for conda?
> 
> What do you mean? Where do we explain what is needed to build the documentation?

I meant
```
diff --git a/README.md b/README.md
index 281bb89..12d7cc3 100644
--- a/README.md
+++ b/README.md
@@ -97,6 +97,7 @@ dependencies with conda. Download and install
     conda create -n e-antic-build ccache
     conda env update -n e-antic-build -f libeantic/environment.yml
     conda env update -n e-antic-build -f pyeantic/environment.yml
+    conda env update -n e-antic-build -f doc/environment.yml
     conda activate e-antic-build
     export CPPFLAGS="-isystem $CONDA_PREFIX/include"
     export CFLAGS="$CPPFLAGS"
```

2021-01-31 22:03 UTC, videlec commented
Something is not careful enough
```
make[2]: Entering directory '/home/vincent/programming/flatsurf/e-antic/doc/manual'
mkdir -p ./markdown
ln -s ../html/pyeantic ./markdown/pyeantic
ln: failed to create symbolic link './markdown/pyeantic': File exists
make[2]: *** [Makefile:424: markdown/pyeantic] Error 1
```

2021-01-31 22:08 UTC, saraedum commented
> Something is not careful enough

True. A broken symlinks counts as non-existant. Can you try again?

2021-01-31 22:09 UTC, videlec commented
More serious problem [standardese.log](https://github.com/flatsurf/e-antic/files/5900753/standardese.log)

2021-01-31 22:10 UTC, saraedum commented
> More serious problem [standardese.log](https://github.com/flatsurf/e-antic/files/5900753/standardese.log)

Yes. That's a weird problem. I get the same. Working on it…

2021-01-31 22:12 UTC, videlec commented
Yes yes. I got several html files in `doc/build/html`
```
_sources  _static  genindex.html  index.html  objects.inv  overview.html  poly_extra.html  renf.html  renf_elem.html  renfxx.html  search.html  searchindex.js
```

2021-01-31 22:13 UTC, saraedum commented
The standardese error seems to be https://github.com/foonathan/cppast/issues/103.

2021-01-31 22:16 UTC, videlec commented
I don't understand the `index.html` I got. First paragraph is
```
Welcome to E-Antic’s documentation! E-Antic is a C library for rigorous real number field computation. It is thread safe and includes a full featured C++ interface.

E-Antic is distributed under the GNU General Public License (GPL), version 3 (see license).

E-Antic is developed by Vincent Delecroix with help of M. Koeppe and W. Burns. The library also includes the development code of Antic developed by William Hart. It is based on Flint and Arb
```
Where is the source of this? It is not at all what `index.md` contains.

2021-01-31 22:23 UTC, saraedum commented
No. ``grep Burns `find -name index.html` `` does not return anything.

2021-01-31 22:24 UTC, saraedum commented
The "Welcome" sounds like it was made by Sphinx somehow.

2021-01-31 22:27 UTC, saraedum commented
@videlec I guess that's due to the "dirty" build with mkdocs. If there's already an `index.html` that something else created, `mkdocs` will not touch it. I am looking into it…

The weird standardese errors should be gone now btw.

2021-01-31 22:27 UTC, videlec commented
The first error disappered. Now got
```
[preprocessor] [critical] /home/vincent/programming/flatsurf/e-antic/libeantic/e-antic/renfxx_cereal.h:16: 'cereal/cereal.hpp' file not found
[libclang parser] [error] /home/vincent/programming/flatsurf/e-antic/libeantic/e-antic/renfxx.h:77: expected a bracket, got '&'
[libclang parser] [error] /home/vincent/programming/flatsurf/e-antic/libeantic/e-antic/renfxx.h:166: expected a bracket, got '&'
```

2021-01-31 22:29 UTC, saraedum commented
Let's continue here https://sagemath.zulipchat.com/#narrow/stream/271193-polygon/topic/e-antic.20documentation @videlec

2021-02-03 16:06 UTC, saraedum commented
The segfault is fixed in https://github.com/foonathan/cppast/pull/110.

2021-02-03 16:10 UTC, videlec commented
Great, compilation does produce something now :)

2021-05-24 07:41 UTC, videlec commented
@saraedum Is it possible to make reference from the sphinx pyeantic doc to the standardese libeantic doc? For now, it seems to only be used the other way around. But in order to not duplicate the information for eg installation, we would need it.

2021-05-24 13:13 UTC, saraedum commented
> @saraedum Is it possible to make reference from the sphinx pyeantic doc to the standardese libeantic doc? For now, it seems to only be used the other way around. But in order to not duplicate the information for eg installation, we would need it.

Yes, you can use e.g. `` :c++:type:`renf_class` ``.

To see all the possible targets run `python -msphinx.ext.intersphinx doc/manual/generated/libeantic/inventory/objects.inv`

2021-05-24 13:16 UTC, saraedum commented
Some of the targets have somewhat unfortunate names. E.g., header files are referred to by their absolute path which does not make much sense. It's easy to fix if that's something you need as a target.

2021-05-24 17:21 UTC, videlec commented
I wanted to reference the index page of libeantic. Not a specific C or C++ function.

2021-05-24 17:55 UTC, saraedum commented
Could you just link to `../libeantic`?

2021-05-24 18:05 UTC, videlec commented
Trying `../libeantic` in index.rst I got
```
/home/vincent/programming/flatsurf/e-antic/doc/manual/generated/pyeantic/source/usage/quickstart.rst:4:Unknown target name: "../libeantic".
```

2021-05-24 18:06 UTC, videlec commented
(same with `../../libeantic`)

2021-05-24 18:14 UTC, saraedum commented
This works for me `` `libeantic <../libeantic>`_ ``.

2021-06-03 08:26 UTC, videlec commented
Do you understand the failure? A priori it has nothing to do with the documentation
```
  libtool: link: /usr/share/miniconda/envs/test/bin/x86_64-conda-linux-gnu-c++ -std=gnu++14 -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /usr/share/miniconda/envs/test/include -UNDEBUG -Wl,-O2 -Wl,--sort-common -Wl,-z -Wl,relro -Wl,-z -Wl,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath -Wl,/usr/share/miniconda/envs/test/lib -Wl,-rpath-link -Wl,/usr/share/miniconda/envs/test/lib -o renfxx/.libs/t-binop renfxx/t-binop.o main.o -Wl,--as-needed   -L/usr/share/miniconda/envs/test/lib ../src/.libs/libeantic.so ../srcxx/.libs/libeanticxx.so /home/runner/work/e-antic/e-antic/libeantic/src/.libs/libeantic.so -lgmpxx -larb -lantic -lflint -lmpfr -lgmp
  /usr/share/miniconda/envs/test/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: renfxx/t-assignment.o: in function `(anonymous namespace)::RenfClassGenerator::get() const':
  t-assignment.cpp:(.text._ZNK12_GLOBAL__N_118RenfClassGenerator3getEv+0x5e): undefined reference to `eantic::renf_class::make(renf const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
  collect2: error: ld returned 1 exit status
```

2021-06-12 10:09 UTC, saraedum commented
> Do you understand the failure? A priori it has nothing to do with the documentation
> 
> ```
>   libtool: link: /usr/share/miniconda/envs/test/bin/x86_64-conda-linux-gnu-c++ -std=gnu++14 -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /usr/share/miniconda/envs/test/include -UNDEBUG -Wl,-O2 -Wl,--sort-common -Wl,-z -Wl,relro -Wl,-z -Wl,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath -Wl,/usr/share/miniconda/envs/test/lib -Wl,-rpath-link -Wl,/usr/share/miniconda/envs/test/lib -o renfxx/.libs/t-binop renfxx/t-binop.o main.o -Wl,--as-needed   -L/usr/share/miniconda/envs/test/lib ../src/.libs/libeantic.so ../srcxx/.libs/libeanticxx.so /home/runner/work/e-antic/e-antic/libeantic/src/.libs/libeantic.so -lgmpxx -larb -lantic -lflint -lmpfr -lgmp
>   /usr/share/miniconda/envs/test/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: renfxx/t-assignment.o: in function `(anonymous namespace)::RenfClassGenerator::get() const':
>   t-assignment.cpp:(.text._ZNK12_GLOBAL__N_118RenfClassGenerator3getEv+0x5e): undefined reference to `eantic::renf_class::make(renf const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
>   collect2: error: ld returned 1 exit status
> ```

Looks like a symbol is not exported properly.

2021-06-13 08:02 UTC, saraedum commented
@videlec I think this is finally ready. Is there anything you want to add before we merge here?

2021-06-13 09:38 UTC, slel requested changes
A few typos and a few suggested rewordings.
Feel free to disagree with or ignore any of them.

More general comments:

- I would use sentence case for all document titles and headers,
  as recommended by several code style guidelines including Google's:
  https://developers.google.com/style/capitalization#capitalization-in-titles-and-headings

- The link to the GNU licenses is sometimes given as http, sometimes as https,
  maybe be consistent and pick one or the other.

  http://www.gnu.org/licenses/
  https://www.gnu.org/licenses/

2021-06-13 09:38 UTC, slel commented on libeantic/e-antic/fmpz_poly_extra.h
> +/// `pol` (currently using Decartes rule of sign).
Decartes -> Descartes, add apostrophe, sign -> signs
so altogether:
Decartes rule of sign -> Descartes' rule of signs
see https://en.wikipedia.org/wiki/Descartes%27_rule_of_signs

2021-06-13 09:38 UTC, slel commented on libeantic/e-antic/fmpz_poly_extra.h
> +/// of the polynomial `(p, len)` using Decartes rule of sign. If
Decartes -> Descartes, add apostrophe, sign -> signs
so altogether:
Decartes rule of sign -> Descartes' rule of signs
see https://en.wikipedia.org/wiki/Descartes%27_rule_of_signs

2021-06-13 09:38 UTC, slel commented on libeantic/e-antic/fmpz_poly_extra.h
> +/// the exact diadic roots found by the algorithm and
dyadic is the more common spelling
diadic -> dyadic

2021-06-13 09:38 UTC, slel commented on libeantic/e-antic/fmpz_poly_extra.h
> +/// `exact_roots` will be set by the exact diadic roots found
dyadic is the more common spelling
diadic -> dyadic

2021-06-13 09:38 UTC, slel commented on libeantic/e-antic/renf_class.hpp
> +    /// Return a human-readabie representation of this field.
readabie -> readable

2021-06-13 09:38 UTC, slel commented on libeantic/e-antic/renf_class.hpp
> +    /// // There is also an operator<< which gives the same output.
space between "operator" and "<<"?
operator<< -> operator <<

2021-06-13 09:38 UTC, slel commented on libeantic/e-antic/renf_elem.h
> +/// All the binary operations functions are of the form `renf_elem_OP_TYP(a, b, c, nf)` where
binary operations functions -> binary operation functions

2021-06-13 09:38 UTC, slel commented on libeantic/e-antic/renf_elem.h
> +/// [renf_elem_floor]. Though, this function is much faster.
Though, this function is much faster. -> This function is much faster, though.

2021-06-13 09:38 UTC, slel commented on libeantic/e-antic/renf_elem_class.hpp
> +/// fields they are contained in. The number field will be kept alive by smart
the lifetimes of the number fields -> the lifetime of the number field

2021-06-13 09:38 UTC, slel commented on libeantic/e-antic/renf_elem_class.hpp
>  LIBEANTIC_API renf_elem_class pow(const renf_elem_class& x, int exp);
Should triple slash be used here instead of double slash?

2021-06-13 09:38 UTC, slel commented on libeantic/test/byexample/extensions/cxx.py
> +written cling syntax which is somewhat cryptic to readers not familiar with
writte cling syntax -> written in cling syntax

2021-06-13 09:38 UTC, slel commented on libeantic/test/byexample/extensions/cxx.py
> +MarkDown code fences and expected outputs in `// ->` comments.
MarkDown -> Markdown

2021-06-13 09:38 UTC, slel commented on libeantic/test/byexample/extensions/cxx.py
> +We also use cppyy instead of cling which takes care of the hard part of the
add comma after cling

2021-06-13 09:38 UTC, slel commented on libeantic/test/byexample/extensions/cxx.py
> +    Detect C/C++ examples in MarkDown comments in Header files like the ones
MarkDown -> Markdown
Header -> header

2021-06-13 09:38 UTC, slel commented on libeantic/test/byexample/extensions/cxx.py
> +    Detects C/C++ examples in MarkDown.
MarkDown -> Markdown

2021-06-13 09:38 UTC, slel commented on libeantic/test/byexample/extensions/cxx.py
> +            # Begin with a markdown fenced-code marker
markdown -> Markdown

2021-06-13 09:38 UTC, slel commented on libeantic/test/byexample/extensions/cxx.py
> +            # Begin with a markdown fenced-code marker
markdown -> Markdown

2021-06-13 09:38 UTC, slel commented on libeantic/test/byexample/extensions/cxx.py
> +    Detects blocks of C++ code delimited ended by a `// ->` comment that provides the expected output.
Detects -> Detect
Is "delimited ended" a typo?

2021-06-13 09:38 UTC, slel commented on libeantic/test/byexample/extensions/cxx.py
> +                  (?P<indent> [ ]* (?:///[ ])?)     # an arbitrary amount of indent (we capture it so we can strip it later)
possibly shorten comment:
arbitrary indent, captured so we can strip it later

2021-06-13 09:38 UTC, slel commented on libeantic/test/byexample/extensions/cxx.py
> +            (?:[ ]* (?:///[ ]*)?\n)*                # Finally, consume empty lines so that they do not confuse the indent detection of the next block
possibly shorten comment to:
finally, consume empty lines to prevent confusing indent detection of next block

2021-06-13 09:38 UTC, slel commented on pyeantic/src/pyeantic/realalg_conversion.py
> +similarly to ``pyeantic`` exact computations over real embedded number field.
number field. -> number fields.

2021-06-13 09:54 UTC, saraedum commented
> A few typos and a few suggested rewordings.
Thanks for the feedback. I converted everything to suggestions (there's a +/- button when you write a code comment. This creates a patch which makes merging more convenient, see below.)

>     * I would use sentence case for all document titles and headers,
I've been trying to use title case in all the flatsurf projects. I have no objections to changing that.

>     * The link to the GNU licenses is sometimes given as http, sometimes as https,
It should always be https. I fixed it.

2021-06-13 12:07 UTC, slel requested changes
Thanks for addressing some of my punctual comments
and commenting on the general ones.

Ok for title case if it's a deliberate choice, though
it's harder to get right and to keep consistent.

I'm pointing to a few typos I missed in my first pass.

My first review was so long GitHub gave a condensed view,
with a word in the middle reading "21 conversations skipped"
and a "Load more..." link; maybe you missed that, please check.
Suggestions like "documentaion -> documentation" in particular
are noncontroversial, making me think you did not see them.

Some case variations coexist and might be made
consistent: FLINT vs Flint, Conda vs conda. Or not.
Likewise, should sphinx be Sphinx throughout?

2021-06-14 08:18 UTC, saraedum commented
@slel you are right. I missed the collapsed suggestions. Thanks for double checking.

2021-06-14 08:20 UTC, saraedum commented on libeantic/e-antic/renf_elem_class.hpp
>  LIBEANTIC_API renf_elem_class pow(const renf_elem_class& x, int exp);
No, this one is intentional. With double-slashes it won't show up in the documentation and we do not want these to show up there.

2021-06-14 08:23 UTC, saraedum commented on doc/manual/libeantic/overview_c.md
> +1$, represented by an `fmpq_poly_t`.
```suggestion
We want to construct a totally real field with minimal polynomial $x^3 - 3x +
1$, represented by an `fmpq_poly_t`. We include the appropriate headers and
define the polynomial.
```

2021-06-14 08:28 UTC, saraedum commented on libeantic/e-antic/renf_class.hpp
> +    /// // There is also an operator<< which gives the same output.
I think `operator<<` is the more common name for this.

2021-06-14 08:28 UTC, saraedum commented on libeantic/test/byexample/extensions/cxx.py
> +We also use cppyy instead of cling which takes care of the hard part of the
I learned not to put a comma in this place.

2021-06-14 08:32 UTC, saraedum commented
Now it seems that I did not miss any conversations. I will merge and release a final rc once the CI is happy.

2021-06-14 08:34 UTC, saraedum commented
> Some case variations coexist and might be made
consistent: FLINT vs Flint, Conda vs conda. Or not.
Likewise, should sphinx be Sphinx throughout?

I don't know. I try to use the name that the project itself uses. I guess it would be nice to be consistent.

2021-06-14 09:10 UTC, merged

2021-06-14 10:36 UTC, slel reviewed
Thanks for expanding the collapsed view and going through
all my little quibbles! And good that you merged.

2021-06-14 10:36 UTC, slel commented on libeantic/test/byexample/extensions/cxx.py
> +We also use cppyy instead of cling which takes care of the hard part of the
I know there are several similar cases where
there's a comma in German but not in English
(like before "where" in this sentence, probably).

To me the comma changes the meaning here,
making "which" apply to "we use" instead of
applying to "cling". Parenthesising as in math
to emphasize what I mean:
- "instead of (cling which takes care of ...)"
  (compare: "instead of cling which is slower")
- "(We also use ...), which takes care of ..."

But I may be wrong. Besides, the intention is clear
if one is not purposefully playing getting it wrong
for the sake of discussion like I am.  : )

One option would be to rephrase as one of:
- Using cppyy instead of cling takes care of ...
- Instead of cling we also use cppyy which takes care of ...
But again, it's also fine to leave as is.

2021-06-14 11:00 UTC, saraedum commented
Thanks for clarifying. I think rephrasing is better. I'll push changes with your first proposal directly.