Add pull request template
flatsurf/e-antic pull request #219
Opened 2021-11-23 02:00 UTC by saraedum

2021-11-23 02:00 UTC, saraedum commented
I don't deem this news-worthy and there's nothing to test :)

2021-11-23 02:03 UTC, merged

2021-11-23 02:05 UTC, slel requested changes

2021-11-23 02:05 UTC, slel commented on .github/pull_request_template.md
> +Thank you for pull request.
Thank you for submitting a pull request.

2021-11-23 03:31 UTC, saraedum commented on .github/pull_request_template.md
> +Thank you for pull request.
Lol, I copied this from conda-forge's pull request template, so I didn't even proof read that part:

![image](https://user-images.githubusercontent.com/373765/142967391-3e9ff783-dc3f-4e38-8eac-2f439d250caa.png)

@isuruf, were you aware of this error? Where can this be fixed?

2021-11-23 12:28 UTC, slel commented
Really, no need to change it. It goes straight to the point.
How to choose between "for working on a pull request",
"for this pull request", "for your pull request", etc.  : )

2021-11-24 06:32 UTC, isuruf commented on .github/pull_request_template.md
> +Thank you for pull request.
Source is at https://github.com/conda-forge/.github/blob/master/.github/PULL_REQUEST_TEMPLATE.md

2021-11-24 06:48 UTC, saraedum commented on .github/pull_request_template.md
> +Thank you for pull request.
Thanks. Fixed in https://github.com/conda-forge/.github/pull/8/files.